---
build_from:
  amd64: docker.io/thibaudmathieu/mopidy-hassio:new
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Mopidy"
  org.opencontainers.image.description: "Media player Mopidy"
  org.opencontainers.image.source: "https://github.com/enlight3d/addon-mopidy"
  org.opencontainers.image.licenses: "Apache License 2.0"
